### ISSUE TITLE
Terraform v0.7 compatibility

### ISSUE THREAD

**Issue by wallies** [Capgemini/kubeform#153]

**Comment by ipedrazas** [comment]
We're in a bit of a mess here. You cannot create a Docker image to use kubeform because TF 0.6.16 is dynamically linked  which makes #93 impossible. But if we create a Docker image with TF 0.7 your templates do not work.

Ideally, we want to upgrade TF (I have the Dockerfile for ansible 2.0.2 and TF 0.7)

Have you evaluated how much work does it mean to upgrade?

**Comment by enxebre** [comment]
Thanks for feedback! yep, we'd definitely like to upgrade to ansible 2.0.2 and TF 0.7 and we'd love to get contributions as well, as we don't have as many hands as we like working on this, we need to prioritise :)
